//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfAppPressure.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7g6d9m4022q43cznu7z31qduqd3gk6tr4sa8n64jnc58cynv4bl9xbvrcmw5tyq6i9akc1axcqpyvfs20" +
            "hljuu337s5aj8zzv8zdyctcay6gv66634fmmhlyfgmt69ne1ze9dc0fc6c94a058666bea2b976f9fd9" +
            "9d381baa808b95c6833b399201f031912cwqpdyxii6xxhaw8hp3mmowb7rz9gbk2p63jqo0qyd9par9" +
            "l7728komy9orw8")]
        public string token {
            get {
                return ((string)(this["token"]));
            }
            set {
                this["token"] = value;
            }
        }
    }
}
